"""Small helpers for writing the committed markdown reports.

Reports live under ``reports/`` and are checked in on purpose: a reviewer should
be able to read the results of every stage straight from GitHub without cloning
the repository or running the pipeline.
"""

from __future__ import annotations

import datetime as _dt
import json
import logging
from pathlib import Path

import pandas as pd

from mkopo.config import REPORT_DIR

log = logging.getLogger(__name__)


def markdown_table(frame: pd.DataFrame, *, floatfmt: str = "{:,.4g}") -> str:
    """Render a DataFrame as a GitHub-flavoured markdown table."""

    def fmt(value: object) -> str:
        if value is None or (isinstance(value, float) and pd.isna(value)):
            return "—"
        if isinstance(value, float):
            return floatfmt.format(value)
        if isinstance(value, (int,)) and not isinstance(value, bool):
            return f"{value:,}"
        return str(value)

    header = "| " + " | ".join(str(c) for c in frame.columns) + " |"
    divider = "|" + "|".join("---" for _ in frame.columns) + "|"
    rows = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in frame.itertuples(index=False)]
    return "\n".join([header, divider, *rows])


def write_report(name: str, title: str, sections: list[tuple[str, str]]) -> Path:
    """Write ``reports/<name>.md`` from ``(heading, body)`` sections."""
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    stamp = _dt.datetime.now().strftime("%Y-%m-%d")
    parts = [f"# {title}", "", f"*Generated by the Mkopo pipeline on {stamp}. Do not edit by hand.*", ""]
    for heading, body in sections:
        if heading:
            parts.append(f"## {heading}")
            parts.append("")
        parts.append(body.rstrip())
        parts.append("")
    path = REPORT_DIR / f"{name}.md"
    path.write_text("\n".join(parts), encoding="utf-8")
    log.info("wrote %s", path)
    return path


def write_metrics(name: str, payload: dict) -> Path:
    """Persist a machine-readable metric blob next to the markdown report."""
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORT_DIR / f"{name}.json"
    path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    log.info("wrote %s", path)
    return path


def read_metrics(name: str) -> dict:
    path = REPORT_DIR / f"{name}.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))
