"""Render docs/data-dictionary.md from the feature contract in mkopo.data.schema.

Keeping the documentation generated means it cannot drift away from the code.
"""

from __future__ import annotations

from pathlib import Path

from mkopo.config import PROJECT_ROOT
from mkopo.data.schema import FAMILIES, FEATURES, MODELLED_FEATURES, PROTECTED_FEATURES

FAMILY_TITLES = {
    "demographic": "Demographic",
    "identity": "Identity and tenure",
    "income": "Income",
    "cashflow": "Cash flow and liquidity",
    "obligations": "Bills and recurring obligations",
    "spending": "Spending and savings",
    "behaviour": "Behavioural risk signals",
    "credit": "Credit history",
    "mobility": "Mobility and network",
}

HEADER = """# Data dictionary

*Generated by `scripts/render_data_dictionary.py` — do not edit by hand.*

Every field below is **synthetic**. It is produced by `mkopo.data.generator`, which
builds a causal graph from livelihood segment to latent income stability and
financial discipline, and from there to observable mobile-money behaviour. No real
customer data is used anywhere in this repository.

- **{n_total}** fields total, **{n_modelled}** of which the model is allowed to see
- **{n_protected}** protected attributes, excluded from the model and audited in
  `mkopo.evaluation.fairness`
- Risk direction records the sign a credit reviewer would insist on; it drives
  monotonic constraints in the gradient booster and is asserted in the test suite

"""

DIRECTION = {1: "↓ risk", -1: "↑ risk", 0: "—"}


def render() -> str:
    parts = [
        HEADER.format(
            n_total=len(FEATURES),
            n_modelled=len(MODELLED_FEATURES),
            n_protected=len(PROTECTED_FEATURES),
        )
    ]
    for family in FAMILIES:
        members = [f for f in FEATURES if f.family == family]
        parts.append(f"## {FAMILY_TITLES.get(family, family.title())}\n")
        parts.append("| Field | Type | Modelled | Risk direction | Description |")
        parts.append("|---|---|---|---|---|")
        for f in members:
            modelled = "yes" if f.modelled else ("**protected**" if f.protected else "no")
            parts.append(
                f"| `{f.name}` | {f.dtype} | {modelled} | {DIRECTION[f.risk_direction]} | {f.description} |"
            )
        parts.append("")

    parts.append("## Targets and flags\n")
    parts.append("| Field | Description |")
    parts.append("|---|---|")
    parts.append(
        "| `approved` | Whether the legacy rules engine disbursed the loan. ~62% of applications. |"
    )
    parts.append(
        "| `default_flag` | 30+ days past due within 90 days. **Observed only where `approved = 1`** — this is the selection bias reject inference corrects. |"
    )
    parts.append(
        "| `true_default_flag` | Counterfactual outcome for every applicant, including rejects. Lives in `data/raw/oracle.parquet` and is never available to a model; it exists so reject inference can be measured rather than asserted. |"
    )
    parts.append(
        "| `application_month` | Month index 0–17. A macro squeeze begins at month 13; months 14–17 form the out-of-time window. |"
    )
    parts.append("")
    return "\n".join(parts)


def main(_argv: list[str] | None = None) -> int:
    out = Path(PROJECT_ROOT) / "docs" / "data-dictionary.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
